[package]
name = "eth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ethers = "2.0.10"
bigdecimal = "0.3.1"
rustc-hex = "2.1.0"
diesel = { version = "2.1.1", features = ["postgres", "numeric", "chrono"] }
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.37"
async-trait = "0.1.74"
ethrpc = { version = "0.0.8", features = ["http"] }
solabi = "0.2.0"

[dev-dependencies]
maplit = "1.0.2"
tracing-test = "0.2.4"
