FROM rust:latest

RUN apt-get update && apt-get install -y libpq-dev

# Install diesel_cli
RUN cargo install --debug diesel_cli --no-default-features --features postgres

# Set the working directory to /app
WORKDIR /app

# Copy the relevant files:
COPY event-handler/src/schema.rs /app/event-handler/src/
COPY diesel.toml /app
COPY event-handler/migrations/ /app/event-handler/migrations/

# Wait for DB to be ready.
COPY test_db/wait-for-it.sh /app
RUN chmod +x /app/wait-for-it.sh

# Run the migrations
#CMD ["diesel", "migration", "run"]
CMD ["./wait-for-it.sh", "postgres-db:5432", "--", "diesel", "migration", "run"]
