[package]
name = "event-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
diesel = { version = "2.1.1", features = [
    "postgres",
    "numeric",
    "serde_json",
    "chrono",
] }
event-retriever = { path = "../event-retriever" }
eth = { path = "../eth" }
tracing = "0.1.37"
tokio = { version = "1.33.0", features = ["macros"] }
serde_json = "1.0.107"
bigdecimal = { version = "0.3.1", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
tracing-subscriber = "0.3.17"

[dev-dependencies]
dotenv = "0.15.0"
