apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ProjectName }}-{{ .Network }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .ProjectName }}
  template:
    metadata:
      labels:
        app: {{ .ProjectName }}
    spec:
      initContainers:
        - name: migration
          image: {{ .ContainerRepo }}/mintbase/{{ .ProjectName }}-migration:{{ .ImageTag }}
          env:
            - name: STORE_URL
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: STORE_URL
            - name: NETWORK
              value: {{ .Network }}
            - name: DB_HOST_PORT
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: DB_HOST_PORT

      containers:
      - name: {{ .ProjectName }}
        image: {{ .ContainerRepo }}/mintbase/{{ .ProjectName }}:{{ .ImageTag }}
        imagePullPolicy: Always
        args: ["event-handler"]
        env:
          - name: LOG
            value: "info,event_handler=debug,eth=debug"
          - name: DB_SCHEMA
            value: {{ .Network }}
          - name: CHAIN_SOURCE
            value: "database"
          - name: PAGE_SIZE
            value: "25"
          - name: NODE_URL
            valueFrom:
              secretKeyRef:
                name: indexer-secrets
                key: NODE_URL

          - name: SOURCE_URL
            valueFrom:
              secretKeyRef:
                name: indexer-secrets
                key: SOURCE_URL

          - name: STORE_URL
            valueFrom:
              secretKeyRef:
                name: indexer-secrets
                key: STORE_URL

#      - name: {{ .ProjectName }}-pubsub
#        image: {{ .ContainerRepo }}/mintbase/{{ .ProjectName }}:v0.0.3-metadata-test3
#        imagePullPolicy: Always
#        args: [ "metadata-retriever" ]
#        ports:
#          - containerPort: 8681
#        env:
#          - name: TOPIC_NAME
#            value: projects/eth-cloud-mb/topics/{{ .Network }}
#          - name: SUBSCRIPTION_NAME
#            value: projects/eth-cloud-mb/subscriptions/metadata-retriever
#
#          - name: DB_SCHEMA
#            value: {{ .Network }}
#
#          - name: SOURCE_URL
#            valueFrom:
#              secretKeyRef:
#                name: indexer-secrets
#                key: SOURCE_URL
#
#          - name: ETHERSCAN_KEY
#            valueFrom:
#              secretKeyRef:
#                name: indexer-secrets
#                key: ETHERSCAN_KEY
#
#          - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
#            valueFrom:
#              secretKeyRef:
#                name: indexer-secrets
#                key: GOOGLE_APPLICATION_CREDENTIALS_JSON
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .ProjectName }}-load-balancer
spec:
  selector:
    app: {{ .ProjectName }}
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8681  # Container port
  type: LoadBalancer