name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: bh2smith/test-events:latest
#        env:
#          POSTGRES_PASSWORD: postgres
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo fmt --check && cargo clippy --all-targets --verbose
