name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint & Clippy
        run: cargo fmt --check && cargo clippy --all-targets --verbose -- -D warnings

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Tests
        # This is so Database tests don't run in parallel!
        run: cargo test -- --test-threads 1

      - name: Stop Docker Compose
        run: docker-compose down
