name: Cargo Test

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Tests
        run: cargo test

      - name: Stop Docker Compose
        run: docker-compose down
